artifact_uri: /home/lennardong/Documents/yoshi_optionstrading/localhost:8081/0/159aafe7aa1a480380a5aeea831d4277/artifacts
end_time: 1733799361403
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 159aafe7aa1a480380a5aeea831d4277
run_name: loud-newt-302
run_uuid: 159aafe7aa1a480380a5aeea831d4277
source_name: ''
source_type: 4
source_version: ''
start_time: 1733799361397
status: 3
tags: []
user_id: lennardong
