artifact_location: /home/lennardong/Documents/yoshi_optionstrading/localhost:8081/0
creation_time: 1733799361317
experiment_id: '0'
last_update_time: 1733799361317
lifecycle_stage: active
name: Default
